language: python

services:
- docker

python:
  - "2.7"
  - "3.6"

script:
  - pip install -r requirements.txt
  - python report.py
  - ls -l
  - test -f ./index.html
  - cat ./index.html

after_script:
  - set -e
  - docker build -t circa10a/device-monitor-dashboard .
  - docker run --rm -d --name monitor circa10a/device-monitor-dashboard
  - sleep 10
  - docker ps | grep monitor
  - docker login -u=circa10a -p=$docker_password
  - docker push circa10a/device-monitor-dashboard
